services:
  - type: web
    name: neuroguardai-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    autoDeploy: true
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FRONTEND_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
